### ISSUE TITLE
Make configure script detection more robust

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#51]
Currently, autotools configure scripts are the only ones supported. A new configure, make, install builder should be included when a configure script is present but isn't an Autotools script. Ideally, we should be able to detect the presence of Autotools configure scripts without running `./configure --version` as some configure scripts don't respect those flags and will start the configure process.

As an example, FFmpeg could be more easily configured:

```
ffmpeg:
    repository: git://source.ffmpeg.org/ffmpeg.git
    commit: n3.0.2
    dependencies:
        - x264
    project:
        environment:
            PKG_CONFIG_PATH: '{{ build_directory('x264') }}/lib/pkgconfig:{current}'
        build-steps:
            - ./configure --prefix={build_directory} --enable-gpl --enable-libx264
            - make -j8 install
```

Ideally this would be the library configuration:

```
ffmpeg:
    repository: git://source.ffmpeg.org/ffmpeg.git
    commit: n3.0.2
    dependencies:
        - x264
    project:
        configure-args:
            - --enable-gpl
            - --enable-libx264
```
