### ISSUE TITLE
Add pkgconfig paths to dependent libraries

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#52]
As an example, if a library depends on another and knows how to use `.pc` files, needy should automatically include that path in the `PKG_CONFIG_PATH` environment variable for the dependent library.

Example:

```
ffmpeg:
    repository: git://source.ffmpeg.org/ffmpeg.git
    commit: n3.0.2
    dependencies:
        - x264
    project:
        environment:
            PKG_CONFIG_PATH: '{{ build_directory('x264') }}/lib/pkgconfig:{current}'
        build-steps:
            - ./configure --prefix={build_directory} --disable-yasm --enable-gpl --enable-libx264
            - make -j8 install
```

Ideally, `PKG_CONFIG_PATH` would not need to be overridden.

```
ffmpeg:
    repository: git://source.ffmpeg.org/ffmpeg.git
    commit: n3.0.2
    dependencies:
        - x264
    project:
        build-steps:
            - ./configure --prefix={build_directory} --disable-yasm --enable-gpl --enable-libx264
            - make -j8 install
```
