### ISSUE TITLE
Assert that somefile.x is present after building.

### ISSUE THREAD

**Issue by ccbrown** [ccbrown/needy#62]
If there's a problem with a build, this will save time by erroring out immediately, and making it really clear where the error occurred. Usage might look something like...

```
libraries:
    hiredis:
        repository: git@github.com:redis/hiredis.git
        commit: v0.13.2
        project:
            expects: lib/libhiredis.a
```

**Comment by ccbrown** [comment]
It also makes sense to allow negation:

```
libraries:
    hiredis:
        repository: git@github.com:redis/hiredis.git
        commit: v0.13.2
        project:
            ensures: lib/libhiredis.a !lib/libhiredis.dylib
```

And in those cases, maybe Needy should just delete files that shouldn't be there.
