### ISSUE TITLE
Add support for host-only build tools

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#70]
In many cases specific build tools are required for compilation on multiple architectures. Examples include NASM, YASM, and GNU make.

Needy should provide a separate top-level directive for tools that are managed much like libraries except that they only target the host architecture.

```
tools:
    nasm:
        download: 'http://www.nasm.us/pub/nasm/releasebuilds/2.11.06/nasm-2.11.06.tar.bz2'
        checksum: 'eaad6f440d3f8d2172d7fd93bed224d4052b904f'
```
