### ISSUE TITLE
Add .needyconfig files for project and user level configurations

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#79]
Needy cache configuration is a configuration that would be great to have as a user or global setting instead of a per-project setting.

Allow `.needyconfig` files to be used at the project level or at the user level.

**Comment by vmrob** [comment]
RFC:

I'm going to propose the following:

# Examples

.needyconfig
```
cache:
    - "relative/path/from/.needyconfig"
    - "/absolute/path"
```

Future possibilities:

```
needs:
    directory: 'some-path'
    recipes:
        - path: 'ssh://user@127.0.0.1/other-org/other-needy-recipes'
          port: 1234
        - 'https://github.com/ccbrown/needy-recipes.git'
platforms:
    android:
        api-level: '17'
        toolchain: 'project/local/android/toolchain/directory'
        runtime: 'libstdc++'
    ios:
        minimum-version: 9
    osx:
        minimum-version: 10.11
    tvos:
        minimum-version: 4
cache:
    - 'relative/path/to/.needyconfig'
    - '/absolute/path'
    - path: 's3://some-bucket'
      allow-write: 'yes'
    - 's3://other-bucket'
```

# CLI

The command line should support setting arguments at the user level (~/.needyconfig) and at the local level (`$(dirname needs.yaml)/.needyconfig`).

```
needy config [<config options>] --set name value
    Sets the configuration for `name` to `value`

needy config [<config options>] --unset name
    Removes the configuration for `name`

needy config [<config options>] --get name
    Queries the configuration value for `name`

needy config [<config options>] --add name value
    Adds a configuration for `value` to `name`. Used for lists.

needy config [<config options>] --remove name value
    Removes the configuration with 'value' from `name`. Used for lists.

config options:
  --global   uses the user configuration file instead of the local one
```

Configurations values are strings or dictionaries (or lists thereof) with a primary key that doubles as a unique identifier (`name` above). This syntax allows for the following identical lists:

```
cache:
    - 'some/path'
    - 's3://some-bucket'
```

```
cache:
    - 'some/path'
    - path: 's3://some-bucket'
```

```
cache:
    - path: 'some/path'
    - path: 's3://some-bucket'
```

With unique paths the impliciation is that the following would be a logic error:

```
cache:
    - path: 'some/path'
    - 'some/path'
```

Possible configuration names:
- needs.directory
- needs.recipes (list, primary key: `path`)
- platforms.android.api-level
- platforms.android.toolchain
- platforms.android.runtime
- platforms.ios.minimum-version
- platforms.osx.minimum-version
- platforms.tvos.minimum-version
- cache (list, primary key: `path`)

```
$ needy config --set needs.directory 'some path'
$ needy config --unset needs.directory
$ needy config --add needs.recipes 'https://github.com/other-org/other-needy-recipes.git'
$ needy config --add needs.recipes --path=s3://some-bucket --allow-write=yes
$ needy config list needs.recipes
  https://github.com/ccbrown/needy-recipes.git
  https://github.com/other-org/other-needy-recipes.git
  s3://some-bucket
      allow-write: yes
$ needy config --remove needs.recipe s3://some-bucket
$ needy config --unset needs.recipes
$ needy config set platforms.android.api-level '17'
$ needy config set platforms.osx.minimum-version '10.11'
$ needy config add cache --path='relative/path/to/.needyconfig'
```

# Inheritance

Some of options are obviously project-local, but many could be put in `~/.needyconfig` and would greatly simplify utilization of needy across the system (specifically with the platforms section).

The order of precedence for configurations would be command line first and `.needyconfig` second. The search order for `.needyconfig` would be `$(dirname needs.yaml)/.needyconfig`  up to `/` with and finally `~/.needyconfig`.

To facilitate inheritance of these configurations, I would also propose that duplicates be allowed _across_ configurations with the merge strategy of configurations to local overwriting global:

~/.needyconfig
```
cache:
    - path: 's3://some-bucket'
      allow-write: yes
```

~/dev/.needyconfig
```
cache:
    - 's3://some-bucket'
    - 'other-path'
```

Result:
```
cache:
    - path: 's3://some-bucket'
      allow-write: yes
    - path: 'other-path
```
