### ISSUE TITLE
Unsupported/unrecognized library keys don't produce errors

### ISSUE THREAD

**Issue by vmrob** [ccbrown/needy#91]
The following project won't produce any errors (assuming `foo` exists and has something in it).

```
libraries:
    foo:
        directory: foo
        asdfasdf:
            - echo hello
```
